const fs = require('fs');
const path = require('path');

const BRAIN_DIR = 'C:\\Users\\scott\\.gemini\\antigravity\\brain';

console.log('--- STARTING COGNITIVE EFFICIENCY & COST TRACKER ---');

function getLatestConversationId() {
  try {
    const dirs = fs.readdirSync(BRAIN_DIR)
      .map(name => ({ name, stat: fs.statSync(path.join(BRAIN_DIR, name)) }))
      .filter(item => {
        if (!item.stat.isDirectory()) return false;
        const logPath = path.join(BRAIN_DIR, item.name, '.system_generated', 'logs', 'transcript.jsonl');
        return fs.existsSync(logPath);
      })
      .sort((a, b) => b.stat.mtime - a.stat.mtime);
    
    return dirs.length > 0 ? dirs[0].name : null;
  } catch (err) {
    console.error('Error reading brain directory:', err);
    return null;
  }
}

const convId = getLatestConversationId();
if (!convId) {
  console.error('No conversation folders found.');
  process.exit(1);
}

const transcriptPath = path.join(BRAIN_DIR, convId, '.system_generated', 'logs', 'transcript.jsonl');
console.log(`Analyzing conversation: ${convId}`);
console.log(`Source Log: ${transcriptPath}`);

if (!fs.existsSync(transcriptPath)) {
  console.error('Transcript file does not exist yet.');
  process.exit(1);
}

const fileContent = fs.readFileSync(transcriptPath, 'utf8');
const lines = fileContent.trim().split('\n');

let totalSteps = 0;
let localActionCount = 0;
let cloudActionCount = 0;
let totalBytesRead = 0; // Input tokens (approx characters / 4)
let totalBytesWritten = 0; // Output tokens (approx characters / 4)
let startTime = null;
let endTime = null;

const toolCallFrequencies = {};

lines.forEach(line => {
  if (!line.trim()) return;
  try {
    const step = JSON.parse(line);
    totalSteps++;
    
    // Timing
    const stepTime = step.created_at ? new Date(step.created_at) : (step.timestamp ? new Date(step.timestamp) : null);
    if (stepTime) {
      if (!startTime || stepTime < startTime) startTime = stepTime;
      if (!endTime || stepTime > endTime) endTime = stepTime;
    }

    // Categorize step source
    if (step.source === 'MODEL') {
      // Generated by the model (Output tokens)
      if (step.thinking) totalBytesWritten += step.thinking.length;
      if (step.content) totalBytesWritten += step.content.length;
      
      if (step.tool_calls && Array.isArray(step.tool_calls)) {
        totalBytesWritten += JSON.stringify(step.tool_calls).length;
        step.tool_calls.forEach(tc => {
          const name = tc.name || '';
          toolCallFrequencies[name] = (toolCallFrequencies[name] || 0) + 1;
          
          const localTools = ['run_command', 'write_to_file', 'replace_file_content', 'multi_replace_file_content', 'list_dir', 'view_file'];
          if (localTools.some(lt => name.toLowerCase().includes(lt))) {
            localActionCount++;
          } else {
            cloudActionCount++;
          }
        });
      }
    } else {
      // Sent to the model as prompt context (Input tokens)
      if (step.content) totalBytesRead += step.content.length;
      if (step.tool_calls) totalBytesRead += JSON.stringify(step.tool_calls).length;
    }
  } catch (e) {
    // Ignore JSON errors
  }
});

// Calculations
const durationMs = endTime - startTime;
const durationMin = durationMs ? (durationMs / 1000 / 60).toFixed(1) : '0';

// Convert characters to estimated tokens (1 token ≈ 4 characters)
const inputTokensEst = Math.round(totalBytesRead / 4);
const outputTokensEst = Math.round(totalBytesWritten / 4);

// Cost Models
// Local stack blended rates ($0.15/M input, $0.60/M output)
const currentCostInput = (inputTokensEst / 1000000) * 0.15;
const currentCostOutput = (outputTokensEst / 1000000) * 0.60;
const currentTotalCost = currentCostInput + currentCostOutput;

// Claude Code stack (Claude 3.5 Sonnet: $3.00/M input, $15.00/M output - assuming 50% caching average = $1.65/M input)
const claudeCostInput = (inputTokensEst / 1000000) * 1.65;
const claudeCostOutput = (outputTokensEst / 1000000) * 15.00;
const claudeTotalCost = claudeCostInput + claudeCostOutput;

const savings = claudeTotalCost - currentTotalCost;
const localPercentage = totalSteps > 0 ? ((localActionCount / (localActionCount + cloudActionCount || 1)) * 100).toFixed(0) : '0';

const reportContent = `# Cognitive Efficiency & Cost Analysis Report

*   **Conversation ID**: \`${convId}\`
*   **Analysis Date**: ${new Date().toLocaleDateString()}
*   **Total Interaction Steps**: ${totalSteps}
*   **Session Duration**: ${durationMin} minutes

---

## 📈 Processing Allocation Split
*   **Local Processing**: **${localPercentage}%** (${localActionCount} local actions)
    *   *Includes file writes, CLI script audits, Git commands, and local directory actions.*
*   **Cloud Reasoning / Search**: **${100 - localPercentage}%** (${cloudActionCount} API transactions)
    *   *Includes web queries, external URL fetches, and LLM completions.*

---

## 💵 Estimated Costs & Savings Metrics

| Metric | Current Stack (Antigravity + Flash/DeepSeek) | Claude Code (Claude 3.5 Sonnet) |
| :--- | :--- | :--- |
| **Est. Input Tokens** | ${inputTokensEst.toLocaleString()} tokens | ${inputTokensEst.toLocaleString()} tokens |
| **Est. Output Tokens** | ${outputTokensEst.toLocaleString()} tokens | ${outputTokensEst.toLocaleString()} tokens |
| **Input Token Cost** | $${currentCostInput.toFixed(5)} | $${claudeCostInput.toFixed(5)} |
| **Output Token Cost** | $${currentCostOutput.toFixed(5)} | $${claudeCostOutput.toFixed(5)} |
| **Total Session Cost** | **$${currentTotalCost.toFixed(4)}** | **$${claudeTotalCost.toFixed(4)}** |

### 🎯 Net Session Savings: **$${savings.toFixed(4)} USD** (${(claudeTotalCost / (currentTotalCost || 1)).toFixed(0)}x cheaper)

---

## 🛠️ Tool Usage Frequencies
${Object.entries(toolCallFrequencies)
  .sort((a, b) => b[1] - a[1])
  .map(([tool, count]) => `*   \`${tool}\`: ${count} calls`)
  .join('\n')}

---

## 💡 Self-Learning Optimization Recommendations
1.  **Read Range Boundaries**: Avoid viewing full files where possible. Limit \`view_file\` calls by using start/end line bounds to save input token storage.
2.  **Combine Terminal Commands**: Chain terminal checks using semicolon operators (e.g. \`git add; git commit\`) to minimize context window processing turns.
3.  **Targeted replacements**: Leverage \`replace_file_content\` chunks instead of full write overrides to keep output generation speeds fast and cost low.
`;

const reportFilePath = path.join(BRAIN_DIR, convId, 'efficiency_report.md');
fs.writeFileSync(reportFilePath, reportContent);

console.log(`✅ Saved efficiency report to: ${reportFilePath}`);
console.log(`Session cost: $${currentTotalCost.toFixed(4)} vs Claude Code: $${claudeTotalCost.toFixed(4)} (Saved $${savings.toFixed(4)})`);
console.log(`Work split: ${localPercentage}% Local vs ${100 - localPercentage}% Cloud`);
console.log('----------------------------------------------------');
